name: coverage
on: 
  push:
    branches:
      - cov_simple
      - main
  pull_request:
    branches:
      - main

# Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "test_coverage"
  test_coverage:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Checkout w support for updating the readme
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
             python -m pip install --upgrade pip
             python -m pip install flake8 pytest pytest-cov
      # Build and install our package in the container
      - name: Build and install the AD project in container
        run: (python -m build --wheel && python -m pip install dist/*)

      # Run the test coverage for the build
      - name: Run tests and generate coverage html
        run: |
             pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov . | tee pytest-coverage.txt

      # Extract info from coverage report using package by MishaKav
      # https://github.com/MishaKav/pytest-coverage-comment
      # https://github.com/MishaKav/pytest-coverage-comment/blob/main/.github/workflows/live-test.yml
      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          default-branch: main
